Django_notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('',include("notes.urls",namespace="Notes")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes/urls.py
from django.contrib import admin
from django.urls import path
from .views import Notelist,finished_item,delete_item,Recover_item,noteform

app_name = "Notes"

urlpatterns = [
    path("",Notelist,name="notelist"),
    path("form",noteform,name="noteform"),
    path("finishitem/<int:id>",finished_item,name="finished_item"),
    path("recoveritem/<int:id>",Recover_item,name="Recover_item"),
    path("deleteitem/<int:id>",delete_item,name="delete_item"),
]

notes/models.py
from django.db import models
from django.shortcuts import redirect,reverse
import django
# Create your models here.
class Note(models.Model):
    LABEL_CHOICES = (
        ('primary','primary'),
        ('success','success'),
        ('secondary','secondary'),
        ('danger','danger'),
        ('warning','warning'),
        ('info','info'),
        ('light','light'),
        ('dark','dark'),
    )
    title = models.CharField(max_length=200)
    due_date = models.DateTimeField(default=django.utils.timezone.now)
    labels = models.CharField(max_length=50,choices=LABEL_CHOICES,default="success")
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    
    class Meta:
        model = Note
        #no need of active field
        fields = ("title","due_date","labels","finished")

notes/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Note
from .forms import NoteForm

# Create your views here
def Notelist(request):
    todo_list =  Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)
    context = {
        "todo_list" : todo_list,
        "finished_list" : finished_list
    }
    return render(request,"note_list.html",context)

def finished_item(request,id):
    note = get_object_or_404(Note,id=id)
    note.finished = True
    note.save()
    return redirect("Notes:notelist")

def Recover_item(request,id):
    note = get_object_or_404(Note,id=id)
    note.finished = False
    note.save()
    return redirect("Notes:notelist")


def delete_item(request,id):
    note = get_object_or_404(Note,id=id)
    note.delete()
    return redirect("Notes:notelist")

def noteform(request):
    note_form = NoteForm(request.POST or None)
    if note_form and note_form.is_valid():
        note_form.save()
        return redirect("Notes:notelist")
    context = {
        "note_form" : note_form
    }
    return render(request,"forms.html",context)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Starter Template · Bootstrap</title>
    <meta name="theme-color" content="#563d7c">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    {% block body %}
    {% endblock body %}
  </div>

</main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

templates/forms.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {{ note_form.as_p }}
        <button type="submit" class="btn btn-success">submit</button>
    </form>
{% endblock body %}

templates/note_list.html
{% extends 'base.html' %}

{% block body %}
<style>
    h4{
        position: relative;
    }
    .icon{
        position: absolute;
        right: 5px;
    }
</style> 
<div class="text-center">
    <h2>Todo List</h2>
</div>
<hr>
    {% for todo in todo_list %}
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h4> {{ todo.title }}
                    <span class="badge badge-{{ todo.labels }}">{{ todo.labels }}</span>
                    {{ todo.due_date }}            
                </h4>
                <span class="icon">
                    <a href="{% url 'Notes:finished_item' todo.id %}"><i class="fa fa-check"></i> </a>
                    <a href="{% url 'Notes:delete_item' todo.id %}"> <i class="fa fa-trash-o"></i></a>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}


    <div class="text-center">
        <h2>Finished List</h2>
    </div>
    <hr>
    {% for finished in finished_list %}
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h4> {{ finished.title }}
                    <span class="badge badge-{{ finished.labels }}">{{ finished.labels }}</span>
                    {{ finished.due_date }}  
                </h4>                        
                <span class="icon">
                    <a href="{% url 'Notes:Recover_item' finished.id %}"><i class="fa fa-check"></i> </a>
                    <a href="{% url 'Notes:delete_item' finished.id %}"> <i class="fa fa-trash-o"></i></a>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock body %}